source "https://github.com/TaranWu/Go23WalletSpec.git"
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!


platform :ios, '13.0'

target 'Go23WalletENS_Example' do
  pod 'Go23WalletENS', :path => '../'

  target 'Go23WalletENS_Tests' do
    inherit! :search_paths

  end
end
